# Generated by Django 5.1.3 on 2024-11-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_members', to='employee.project'),
        ),
    ]
